package grammar.Absyn; // Java Package generated by the BNF Converter.

public class AddAbs extends Addr {
  public final Imm imm_;
  public AddAbs(Imm p1) { imm_ = p1; }

  public <R,A> R accept(grammar.Absyn.Addr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.AddAbs) {
      grammar.Absyn.AddAbs x = (grammar.Absyn.AddAbs)o;
      return this.imm_.equals(x.imm_);
    }
    return false;
  }

  public int hashCode() {
    return this.imm_.hashCode();
  }


}
