package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EBeq extends IInstr {
  public final String reg_1, reg_2;
  public final Addr addr_;
  public EBeq(String p1, String p2, Addr p3) { reg_1 = p1; reg_2 = p2; addr_ = p3; }

  public <R,A> R accept(grammar.Absyn.IInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EBeq) {
      grammar.Absyn.EBeq x = (grammar.Absyn.EBeq)o;
      return this.reg_1.equals(x.reg_1) && this.reg_2.equals(x.reg_2) && this.addr_.equals(x.addr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.reg_1.hashCode())+this.reg_2.hashCode())+this.addr_.hashCode();
  }


}
