package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EJ extends Type {
  public final JOper joper_;
  public final Imm imm_;
  public EJ(JOper p1, Imm p2) { joper_ = p1; imm_ = p2; }

  public <R,A> R accept(grammar.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EJ) {
      grammar.Absyn.EJ x = (grammar.Absyn.EJ)o;
      return this.joper_.equals(x.joper_) && this.imm_.equals(x.imm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.joper_.hashCode())+this.imm_.hashCode();
  }


}
