package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ER1 extends Type {
  public final ROper roper_;
  public final Reg reg_;
  public ER1(ROper p1, Reg p2) { roper_ = p1; reg_ = p2; }

  public <R,A> R accept(grammar.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ER1) {
      grammar.Absyn.ER1 x = (grammar.Absyn.ER1)o;
      return this.roper_.equals(x.roper_) && this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.roper_.hashCode())+this.reg_.hashCode();
  }


}
