package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ESll extends RInstr {
  public final String reg_1, reg_2;
  public final Imm imm_;
  public ESll(String p1, String p2, Imm p3) { reg_1 = p1; reg_2 = p2; imm_ = p3; }

  public <R,A> R accept(grammar.Absyn.RInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ESll) {
      grammar.Absyn.ESll x = (grammar.Absyn.ESll)o;
      return this.reg_1.equals(x.reg_1) && this.reg_2.equals(x.reg_2) && this.imm_.equals(x.imm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.reg_1.hashCode())+this.reg_2.hashCode())+this.imm_.hashCode();
  }


}
