package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EStmtLbl extends Stmt {
  public final LblInstr lblinstr_;
  public EStmtLbl(LblInstr p1) { lblinstr_ = p1; }

  public <R,A> R accept(grammar.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EStmtLbl) {
      grammar.Absyn.EStmtLbl x = (grammar.Absyn.EStmtLbl)o;
      return this.lblinstr_.equals(x.lblinstr_);
    }
    return false;
  }

  public int hashCode() {
    return this.lblinstr_.hashCode();
  }


}
