package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ImmM extends Imm {
  public final Integer integer_;
  public final Reg reg_;
  public ImmM(Integer p1, Reg p2) { integer_ = p1; reg_ = p2; }

  public <R,A> R accept(grammar.Absyn.Imm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ImmM) {
      grammar.Absyn.ImmM x = (grammar.Absyn.ImmM)o;
      return this.integer_.equals(x.integer_) && this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.integer_.hashCode())+this.reg_.hashCode();
  }


}
