package grammar.Absyn; // Java Package generated by the BNF Converter.

public class IOper_lui extends IOper {
  public IOper_lui() { }

  public <R,A> R accept(grammar.Absyn.IOper.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.IOper_lui) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
