package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class IOper implements java.io.Serializable {
  public abstract <R,A> R accept(IOper.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.IOper_addi p, A arg);
    public R visit(grammar.Absyn.IOper_ori p, A arg);
    public R visit(grammar.Absyn.IOper_andi p, A arg);
    public R visit(grammar.Absyn.IOper_slti p, A arg);
    public R visit(grammar.Absyn.IOper_lui p, A arg);
    public R visit(grammar.Absyn.IOper_beq p, A arg);
    public R visit(grammar.Absyn.IOper_bne p, A arg);

  }

}
