package grammar.Absyn; // Java Package generated by the BNF Converter.

public class JOper_j extends JOper {
  public JOper_j() { }

  public <R,A> R accept(grammar.Absyn.JOper.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.JOper_j) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
