package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class JOper implements java.io.Serializable {
  public abstract <R,A> R accept(JOper.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.JOper_j p, A arg);

  }

}
