package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class Label implements java.io.Serializable {
  public abstract <R,A> R accept(Label.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.Lbl1 p, A arg);

  }

}
