package grammar.Absyn; // Java Package generated by the BNF Converter.

public class LbledLine extends LblLine {
  public final Label label_;
  public final Type type_;
  public LbledLine(Label p1, Type p2) { label_ = p1; type_ = p2; }

  public <R,A> R accept(grammar.Absyn.LblLine.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.LbledLine) {
      grammar.Absyn.LbledLine x = (grammar.Absyn.LbledLine)o;
      return this.label_.equals(x.label_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.label_.hashCode())+this.type_.hashCode();
  }


}
