package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ROper_slt extends ROper {
  public ROper_slt() { }

  public <R,A> R accept(grammar.Absyn.ROper.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ROper_slt) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
