package grammar.Absyn; // Java Package generated by the BNF Converter.

public class StmtLblLine extends Stmt {
  public final LblLine lblline_;
  public StmtLblLine(LblLine p1) { lblline_ = p1; }

  public <R,A> R accept(grammar.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.StmtLblLine) {
      grammar.Absyn.StmtLblLine x = (grammar.Absyn.StmtLblLine)o;
      return this.lblline_.equals(x.lblline_);
    }
    return false;
  }

  public int hashCode() {
    return this.lblline_.hashCode();
  }


}
