package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class Type implements java.io.Serializable {
  public abstract <R,A> R accept(Type.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.ER0 p, A arg);
    public R visit(grammar.Absyn.ER1 p, A arg);
    public R visit(grammar.Absyn.ER2 p, A arg);
    public R visit(grammar.Absyn.ER3 p, A arg);
    public R visit(grammar.Absyn.EI p, A arg);
    public R visit(grammar.Absyn.EJ p, A arg);

  }

}
