package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EIInstr extends Instr {
  public final IInstr iinstr_;
  public EIInstr(IInstr p1) { iinstr_ = p1; }

  public <R,A> R accept(grammar.Absyn.Instr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EIInstr) {
      grammar.Absyn.EIInstr x = (grammar.Absyn.EIInstr)o;
      return this.iinstr_.equals(x.iinstr_);
    }
    return false;
  }

  public int hashCode() {
    return this.iinstr_.hashCode();
  }


}
