package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EJ extends JInstr {
  public final Addr addr_;
  public EJ(Addr p1) { addr_ = p1; }

  public <R,A> R accept(grammar.Absyn.JInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EJ) {
      grammar.Absyn.EJ x = (grammar.Absyn.EJ)o;
      return this.addr_.equals(x.addr_);
    }
    return false;
  }

  public int hashCode() {
    return this.addr_.hashCode();
  }


}
