package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EJInstr extends Instr {
  public final JInstr jinstr_;
  public EJInstr(JInstr p1) { jinstr_ = p1; }

  public <R,A> R accept(grammar.Absyn.Instr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EJInstr) {
      grammar.Absyn.EJInstr x = (grammar.Absyn.EJInstr)o;
      return this.jinstr_.equals(x.jinstr_);
    }
    return false;
  }

  public int hashCode() {
    return this.jinstr_.hashCode();
  }


}
