package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EJr extends RInstr {
  public final String reg_;
  public EJr(String p1) { reg_ = p1; }

  public <R,A> R accept(grammar.Absyn.RInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EJr) {
      grammar.Absyn.EJr x = (grammar.Absyn.EJr)o;
      return this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return this.reg_.hashCode();
  }


}
