package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ELui extends IInstr {
  public final String reg_;
  public final Imm imm_;
  public ELui(String p1, Imm p2) { reg_ = p1; imm_ = p2; }

  public <R,A> R accept(grammar.Absyn.IInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ELui) {
      grammar.Absyn.ELui x = (grammar.Absyn.ELui)o;
      return this.reg_.equals(x.reg_) && this.imm_.equals(x.imm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.reg_.hashCode())+this.imm_.hashCode();
  }


}
