package grammar.Absyn; // Java Package generated by the BNF Converter.

public class EStmtInstr extends Stmt {
  public final Instr instr_;
  public EStmtInstr(Instr p1) { instr_ = p1; }

  public <R,A> R accept(grammar.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.EStmtInstr) {
      grammar.Absyn.EStmtInstr x = (grammar.Absyn.EStmtInstr)o;
      return this.instr_.equals(x.instr_);
    }
    return false;
  }

  public int hashCode() {
    return this.instr_.hashCode();
  }


}
