package grammar.Absyn; // Java Package generated by the BNF Converter.

public class ESub extends RInstr {
  public final String reg_1, reg_2, reg_3;
  public ESub(String p1, String p2, String p3) { reg_1 = p1; reg_2 = p2; reg_3 = p3; }

  public <R,A> R accept(grammar.Absyn.RInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.ESub) {
      grammar.Absyn.ESub x = (grammar.Absyn.ESub)o;
      return this.reg_1.equals(x.reg_1) && this.reg_2.equals(x.reg_2) && this.reg_3.equals(x.reg_3);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.reg_1.hashCode())+this.reg_2.hashCode())+this.reg_3.hashCode();
  }


}
