package grammar.Absyn; // Java Package generated by the BNF Converter.

public class LbledLine extends LblInstr {
  public final Label label_;
  public LbledLine(Label p1) { label_ = p1; }

  public <R,A> R accept(grammar.Absyn.LblInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.LbledLine) {
      grammar.Absyn.LbledLine x = (grammar.Absyn.LbledLine)o;
      return this.label_.equals(x.label_);
    }
    return false;
  }

  public int hashCode() {
    return this.label_.hashCode();
  }


}
