package grammar.Absyn; // Java Package generated by the BNF Converter.

public class LbledStmt extends LblInstr {
  public final Label label_;
  public final Instr instr_;
  public LbledStmt(Label p1, Instr p2) { label_ = p1; instr_ = p2; }

  public <R,A> R accept(grammar.Absyn.LblInstr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.LbledStmt) {
      grammar.Absyn.LbledStmt x = (grammar.Absyn.LbledStmt)o;
      return this.label_.equals(x.label_) && this.instr_.equals(x.instr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.label_.hashCode())+this.instr_.hashCode();
  }


}
