package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class LblInstr implements java.io.Serializable {
  public abstract <R,A> R accept(LblInstr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.LbledStmt p, A arg);
    public R visit(grammar.Absyn.LbledLine p, A arg);

  }

}
