package grammar.Absyn; // Java Package generated by the BNF Converter.

public class OffRel extends Offset {
  public final Integer integer_;
  public final String reg_;
  public OffRel(Integer p1, String p2) { integer_ = p1; reg_ = p2; }

  public <R,A> R accept(grammar.Absyn.Offset.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.OffRel) {
      grammar.Absyn.OffRel x = (grammar.Absyn.OffRel)o;
      return this.integer_.equals(x.integer_) && this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.integer_.hashCode())+this.reg_.hashCode();
  }


}
