package grammar.Absyn; // Java Package generated by the BNF Converter.

public class PDefs extends Program {
  public final ListStmt liststmt_;
  public PDefs(ListStmt p1) { liststmt_ = p1; }

  public <R,A> R accept(grammar.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof grammar.Absyn.PDefs) {
      grammar.Absyn.PDefs x = (grammar.Absyn.PDefs)o;
      return this.liststmt_.equals(x.liststmt_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststmt_.hashCode();
  }


}
