package grammar.Absyn; // Java Package generated by the BNF Converter.

public abstract class RInstr implements java.io.Serializable {
  public abstract <R,A> R accept(RInstr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(grammar.Absyn.EAdd p, A arg);
    public R visit(grammar.Absyn.ESub p, A arg);
    public R visit(grammar.Absyn.EAnd p, A arg);
    public R visit(grammar.Absyn.EOr p, A arg);
    public R visit(grammar.Absyn.ESll p, A arg);
    public R visit(grammar.Absyn.ESrl p, A arg);
    public R visit(grammar.Absyn.ESlt p, A arg);
    public R visit(grammar.Absyn.EJr p, A arg);

  }

}
